### ISSUE TITLE
Questions? 

### ISSUE THREAD

**Issue by fmarletaz** [BenoitMorel/GeneRax#31]
Hi - 
Thanks for developing generax, seems like a very promising tool. I have a few questions: (1) the species tree should be rooted but the root can only be one species from what I experienced, that is quite embarrassing in case one wants to use an outgroup that includes several species and (2) the `reconciliations` output folder is missing in my run, should I activate an option to obtain it? 
Thanks a lot!

**Comment by BenoitMorel** [comment]
Hi @fmarletaz,

(1) I am not sure that I understand why using an outgroup with several species is an issue: once you have identified the root (the top internal node) of the tree thanks to the outgroup, do you still need the outgroup species for the GeneRax analysis? Or do you mean that the different outgroup species define several potential roots?

(2) This is because of a stupid decision from me. You currently need the option --reconcile to obtain the reconciliations. In the next release, I will output the reconciliations by default, without requiring any option.

Benoit

**Comment by fmarletaz** [comment]
Thanks a lot for your reply. 
So, to be more specific about the rooting, if I am running generax with the tree (1) 
`(((Strpur,Acapla),(Sackow,Ptyfla)),((Brabel,(Braflo,Bralan)),(((Letjap,Petmar),Parata),(((Calmil,Chipun)),(((Lepocu,Amical),(Danrer,Orylat)),(Latcha,(Xentro,(Galgal,(Homsap,Musmus)))))))));` 
It crashed with the error: `Error, the following tree should be rooted and is not:deut_simp.tre`
However, if I use this tree: 
`(((((((((((Homsap,Musmus),Galgal),Xentro),Latcha),((Lepocu,Amical),(Danrer,Orylat))),(Calmil,Chipun)),((Letjap,Petmar),Parata)),((Braflo,Bralan),Brabel)),(Sackow,Ptyfla)),Acapla),Strpur);`
everything goes fine (but from what I looked, this distorts a bit the topology for some gene families that have duplication at the root). 
Thanks! Ferdi

**Comment by BenoitMorel** [comment]
Hi Ferdi,

it took some time, but I found the issue. Both your trees are rooted, but the following substring is not supported by our parsers: `((Calmil,Chipun))` because of the redundant parenthesis (it should be `(Calmil,Chipun)`).

For some reason, our code for parsing unrooted trees accepts it, which explains the misleading error message. I will have a look at this to at least return a better error message.

Please let me know if you still get unexpected topologies for gene families that should have a duplication at the root.

Benoit

**Comment by BenoitMorel** [comment]
I am closing the issue, please reopen if needed.

Benoit
