### ISSUE TITLE
generax crashes when reconciling gene trees with the species tree

### ISSUE THREAD

**Issue by tothuhien** [BenoitMorel/GeneRax#34]
Hi,
I'm trying to run generax on ~ 20k gene families and a rooted species tree, but it crashes when starting the to reconcile gene trees with species tree. I've attached here the log file. Could you have a look? 
Thank you very much,
Hien

[generax.log](https://github.com/BenoitMorel/GeneRax/files/4891357/generax.log)

**Comment by BenoitMorel** [comment]
Hi Hien,

There is something weird going on: the likelihood scores do not improve
during the run, but stay constant. So I think that there is already an
issue before the reconciliation step.

Could you send me your family file?
Do you reproduce if you run the same command, but only with the 10 first
families instead of 20000?

Benoit

Le mer. 8 juil. 2020 à 16:48, Thu-Hien To <notifications@github.com> a
écrit :

**Comment by tothuhien** [comment]
Thanks Benoit. I will try with a couple of families and let you know. Do you just want the family file or all the alignments as well (it maybe large)? I can send you via email. 
Actually, the above log file was from the second run, resuming the first run which was also failed before. I attached here the log file of the first run.
[generax1.log](https://github.com/BenoitMorel/GeneRax/files/4896525/generax1.log)
Thank you,

Hien

**Comment by BenoitMorel** [comment]
Hi Hien,

Now it makes more sense. I suspect that there is some numerical issue during the reconciliation process, in one of the families.
If possible, it would be great if you could share your alignments and family file. This issue might not be trivial to fix, and it will be much more convenient if I can reproduce it myself. But I am not sure that you can send such a large dataset per mail.

Benoit

**Comment by tothuhien** [comment]
Hi, I've shared the data via Dropbox. Hope you will receive it. Thanks.

Hien

**Comment by BenoitMorel** [comment]
Thanks, I received it. Could you also send me the species tree?

Benoit

Le ven. 10 juil. 2020 à 09:45, Thu-Hien To <notifications@github.com> a
écrit :

**Comment by BenoitMorel** [comment]
Hi Hien,

I understood what's going on. I read the logs too quickly and did not realize that you are using version 1.2.0
The bug you are encountering was fixed in 1.2.1 (I think you are using bioconda, it's the last release), so I encourage you to update. 

To save you some time, because your analysis is quite long: 
I suggest that you first check that you reproduce the bug with a few families (the last ones maybe, because they are much smaller). Then update generax, and check that you can successfully run it on the few families.

Benoit

**Comment by tothuhien** [comment]
Hi Benoit,

Yes I'm using bioconda. I've tried to reinstall the package again, also tried to specify the package version to 1.2.1 but still when I run generax, it always give me the version v1.2.0. 

_[00:00:00] GeneRax v1.2.0_

Could you have a look again with the version on bioconda? Thank you very much.

Hien

**Comment by BenoitMorel** [comment]
Hi Hien,

yes, you are right, I think I messed up with the log message. The version you have should not have the bug, but to be safe, I submitted a new version (v1.2.2) with the good version name in the logs to bioconda. I will notify you when it's available.

Benoit

**Comment by tothuhien** [comment]
Thanks Benoit. So is the new version the same as the one on GitHub? I can try to install it.

Hien

**Comment by BenoitMorel** [comment]
Hi Hien,

Yes, the master branch corresponds to the most up-to-date stable version.
I am sorry for the bioconda package, for some reason the bioconda team did
not process it yet. I am sending them a reminder.

Benoit

Le mar. 28 juil. 2020 à 08:50, Thu-Hien To <notifications@github.com> a
écrit :

**Comment by BenoitMorel** [comment]
The bioconda package was updated this morning :-)

**Comment by tothuhien** [comment]
Thanks Benoit. I'm rerunning the job with the new version. I'll let you know if the problem is fixed.

Hien

**Comment by tothuhien** [comment]
Hi Benoit,
The run finishes successfully with the new version. Thank you very much for your help.
Hien

**Comment by BenoitMorel** [comment]
Hi Hien,
great that it works, thanks for the feedback
Benoit

Le mar. 4 août 2020 à 08:29, Thu-Hien To <notifications@github.com> a
écrit :
