### ISSUE TITLE
Can I use Reference strain as a rooting strain for a SNP based species tree?

### ISSUE THREAD

**Issue by dineshkumarsrk** [BenoitMorel/GeneRax#45]
I have generated a phylogenetic tree based on whole-genome SNP, wherein I used Reference strain as an outgroup to root my species tree. The gene family tree also includes the reference strain. Is it the correct way to carry out the GeneRax  analysis or should I have to include outgroup organism other than reference strain?.

**Comment by BenoitMorel** [comment]
Hello,

I am not very familiar with SNP analysis, but here is an attempt to answer your question.
From the GeneRax perspective, the presence/absence/nature of outgroup(s) does not matter: the most important is to have a realistic root position (which is given to GeneRax with the top node of the species tree newick file), in particular if you expect duplication/loss events. This is because the root defines the orientation of the species tree, and because gene events are an irreversible process.

Please let me know if this is unclear or if you have further questions :-)
Benoit

**Comment by dineshkumarsrk** [comment]
Thank you @BenoitMorel , for your prompt response. I am satisfied with your explanation, because the reference strain of study is well proven ancestor of other strain included in this study, so with reference to your answer it is not an issue I guess. My gene family tree and my rooted species tree has the same number of strains (Ideally species tree consist of outgroup strain as additional strain, when compare to gene family tree), so it will not create any issue while running GeneRax I hope :-)
