### ISSUE TITLE
recPhyloxml output placing gene branches outside species tree

### ISSUE THREAD

**Issue by MattGoulty** [BenoitMorel/GeneRax#46]
I have run generax with the following options
generax -s MainSample_CATGTR_editedfixed.newick  -f Families_acsc.txt -r UndatedDL -p acsc 

The reconciliation appears to have worked, with the program completing and not showing any error messages but when I visualize the reconciliation .xml file the output is obviously wrong with gene tree branches placed everywhere, violating the bounds of the species tree and not forming any recognizable tree structure.

The output newick genetree file works fine and all the inputs seem correct.

I have emailed you the inputs and the output genetree.newick, .xlm and .svg from recphylo.

Have you encountered this problem before?

**Comment by BenoitMorel** [comment]
Dear Matthew,

Thank you for your report.
I suspect that the issue lies in the support values of the species tree.
The reconciliation format uses the names of the nodes of the species tree
to determine where the events happen. Here, the name of the ancestral
species (internal nodes) is always one, and if GeneRax does not detect and
fix this, it may result in a random display in the viewer.
I thought I had fixed this, but now I realize that I have only taken care
of missing labels, but not of existing redundant labels.

I suggest that you try with a species tree without support values or with
distinct labels on the internal nodes, to see if it solves the problem. On
my side, I will check the code again and properly detect and fix this
problematic case.

Benoit


Le mar. 16 févr. 2021 à 17:16, MattGoulty <notifications@github.com> a
écrit :

**Comment by MattGoulty** [comment]
Hello Benoit

Thank you, I shall give it another go with the altered species tree. Do you think a similar problem would occur due to the gene trees also having node support values as I believe some of my gene trees do?

Thanks,
Matthew
________________________________

**Comment by BenoitMorel** [comment]
Everything should work fine with bootstrap values on gene trees

Le mer. 17 févr. 2021 à 12:15, MattGoulty <notifications@github.com> a
écrit :

**Comment by BenoitMorel** [comment]
The issue with duplicate label names in the species tree should be fixed now. Please reopen if needed!
