### ISSUE TITLE
Compilation Error: Built target pll_obj

### ISSUE THREAD

**Issue by ak-watson** [BenoitMorel/GeneRax#51]
Hit a compilation error and didn't spot it in existing issues so thought I'd flag it. 

Hitting my problem here:

[ 51%] Building C object ext/pll-modules/libs/libpll/src/CMakeFiles/pll_obj.dir/fast_parsimony_avx2.c.o
[ 51%] Built target pll_obj
make: *** [Makefile:84: all] Error 2

For reference:
cmake version 3.16.3
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

Thanks!
Andrew

**Comment by BenoitMorel** [comment]
Dear Andrew,

Could you please post or attach the entire compilation logs?

Best,
Benoit

**Comment by ak-watson** [comment]
Dear Benoit, 

Oh sorry, of course. I meant to include them with the issue, my bad. 

I have attached the generax install log and output. 

Looking at it again, it seems to be a problem with MPIScheduler. 

I remember seeing someone previously had a similar issue that was fixed by rolling back to a different version of cmake.

[generax_install.log](https://github.com/BenoitMorel/GeneRax/files/6357447/generax_install.log)

[generax_install_output.txt](https://github.com/BenoitMorel/GeneRax/files/6357450/generax_install_output.txt)

Best,
Andrew

**Comment by BenoitMorel** [comment]
Hi Andrew,

thanks. The relevant error message is:
In file included from /usr/local/include/assert.h:5,
                 from /usr/include/c++/9/cassert:44,
                 from
/home/andrew/Programs/GeneRax/ext/MPIScheduler/src/main.cpp:6:
/usr/local/include/except.h:15:32: error: conflicting declaration ‘typedef
struct Except_Frame_T* Except_Frame_T’

It's hard to tell what's going on. It looks like there is something wrong
in your assert.h header (it contains some standard C functions that are
called by MPIScheduler).  I have googled the error message, and everytime
the answer is there is something wrong in the user's system. I encourage
you to read the following post: https://github.com/isovic/graphmap/issues/77

In particular, this answer might help:
https://github.com/isovic/graphmap/issues/77#issuecomment-342840966
Do not forget that these headers can be important to compile programs on
your machines. Make sure that you rename them (as done in the linked
answer) instead of removing them, in case you want to rollback the
operation.

Please let me know if it helps or if you need further help :-)
Benoit

**Comment by ak-watson** [comment]
Ah brilliant, thank you.

I renamed the headers and went smoothly from there. 

It is interesting that the post mentions GMAP might be responsible for those headers. I installed GMAP last week, so it makes sense I hadn't seen this issue before.

Just as a quick test, I also compiled GeneRax on another machine I use running on ubuntu 20.04.02 without GMAP installed without any issues. 

Thanks again,
Andrew
