### ISSUE TITLE
Cannot read alignment file

### ISSUE THREAD

**Issue by pd16** [BenoitMorel/GeneRax#63]
Hi,

I'm trying to run generax on 1000s of gene families, which are aligned by mafft but generax is throwing an error(log file attached).

Thansks,
Pankaj 
[files.zip](https://github.com/BenoitMorel/GeneRax/files/10981181/files.zip)

**Comment by BenoitMorel** [comment]
Hi Pankaj,
Everything looks fine to me at first glance. Can you also send me the
family file? (families.tmp)
Benoit

Le mer. 15 mars 2023 à 15:48, Pankaj Dhakad ***@***.***> a
écrit :

**Comment by BenoitMorel** [comment]
Thank you :)
So here is the problem: you are using the model GTR+G, which is a DNA
model. The alignment parser expects DNA characters, but you are using
protein alignments. For protein data, the corresponding model would be
PROTGTR+G (you can find more information here, we use the same notations in
both raxml-ng and generax:
https://github.com/amkozlov/raxml-ng/wiki/Input-data#single-model), but I
strongly discourage you to use it. In short, GTR is a good model for DNA
data, but not for proteins, because  it has way too many free parameters. I
would rather use a predefined protein model such as LG+G for this kind of
problem (or any other model that makes sense for your data).
I'll try to output a more explicit message because I think this confusion
will be made quite often ;-)
Let me know if that solves your problem


Le mer. 15 mars 2023 à 15:58, Pankaj Dhakad ***@***.***> a
écrit :

**Comment by pd16** [comment]
Oh Yes! That worked :)
Thanks
