### ISSUE TITLE
User input --dup-rate and --no-dup

### ISSUE THREAD

**Issue by DhakadPankaj** [BenoitMorel/GeneRax#65]
Hi,
I'm trying to run generax with --dup-rate (for ex. 0.0001, 0.001, 0.01, 0.1) flag but I'm getting the same gene trees every time (PFA std output file) . Also when I provide --no-dup flag I still can see unnecessary duplication and losses in the trees. 
[run.out.txt](https://github.com/BenoitMorel/GeneRax/files/11798620/run.out.txt)

**Comment by BenoitMorel** [comment]
Also, have you installed GneeRax with bioconda or from the github repo?

**Comment by BenoitMorel** [comment]
Sorry for the multiple posts. I have just seen that you provided the logs
in your initial post.

--dup-rate doesn't work because it only sets the starting duplication rate.
If you want to fix the rate, you also need to use --dtl-rates-opt NONE to
disable rate optimization. Note that in this case, the loss and transfer
rates won't be optimized, so maybe you also want to set them yourself.
This is my fault, because those options are not documented in the wiki. I
will update it today.

However, --no-dup should work. It doesn't forbid losses, but it should
forbid duplications. If it doesn't work, can you also send me the files
from at least one family, such that I can reproduce? Thanks :)

**Comment by BenoitMorel** [comment]
This is because --no-dup doesn't make any sense when used with UndatedDL:
the combination of both results in a model that would only allow gene
losses, and couldn't explain gene tree conflict. I will add a check in the
program to forbid this combination and document this in the wiki.

Le mer. 21 juin 2023 à 17:00, Pankaj Dhakad ***@***.***> a
écrit :

**Comment by DhakadPankaj** [comment]
Okay, that make sense. but when I remove UndatedDL I'm getting transfers instead of duplications. 
For my analysis, all I want is minimise overestimation of Duplications and losses when I have one sequence per species. For example in the attached svg file there are 4 duplications but I'm expecting only 3 duplications (at the tips only). So, is there a way to force the gene tree to look like species tree in obvious cases ?
[data_issue_65_2.zip](https://github.com/BenoitMorel/GeneRax/files/11833331/data_issue_65_2.zip)

  

Thanks for your help and updating the wiki!

**Comment by BenoitMorel** [comment]
The whole point of using a software that automatically infers a result from
the data is that you can't force it to output the results you expect. What
GeneRax tells you, is that the most likely explanation (under the
assumptions that the model and the input data are correct!) is that there
were 4 duplications. If you try to force it to get 3 duplications, then you
could as well not use GeneRax at all. Here, it looks like the case is not
obvious: even if the reconciliation is visually not satisfying, the signal
from the sequences indicates an important signal for species tree - gene
tree discordance.

Of course this doesn't mean that there was a duplication. Here are
potential explanations:
- their could be something else going on (here, this could be incomplete
lineage sorting)
- the species tree could be wrong
- maybe the most likely answer (which is what GeneRax returns) is not the
correct one
- something is wrong in the sequences (the alignment, or the sequences
themselves)

In general, I strongly discourage forcing the results by tweaking the input
parameters, because it might compromise the integrity of your research. If
you have independent evidence for an absence of the 4th duplication, I
would rather try to explain why GeneRax could be wrong (which is definitely
possible) than to manipulate the run.




Le jeu. 22 juin 2023 à 13:23, Pankaj Dhakad ***@***.***> a
écrit :

**Comment by DhakadPankaj** [comment]
Hi,
I do understand your points. The example above is just a test case. I'm trying if changing input parameters of Generax could give me more plausible and consistant results. 
Thanks!
